[package]
name = "react"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
langchain-rust = "4.1.3"
futures = "0.3"